### ISSUE TITLE
点击“删除”无法出现删除对话框

### ISSUE THREAD

**Issue by zhongxi-tech** [fyl080801/vjdesign#31]
在设计界面区域内，选中某组件之后，点击“删除”后，本机测试可以出现对话框，而在其他不同IP地址的机器上却无法出现删除对话框
![没有出现删除对话框](https://user-images.githubusercontent.com/60704793/99904378-71aa3a80-2d05-11eb-9650-52fd0854e442.png)

**Comment by fyl080801** [comment]
请问用的是什么浏览器？

**Comment by zhongxi-tech** [comment]
使用的游览器是
Google Chrome
版本 86.0.4240.198（正式版本） （64 位）

**Comment by zhongxi-tech** [comment]
使用本地调试机器上的游览器，可以出现“删除对话框”
![image](https://user-images.githubusercontent.com/60704793/99954644-112b0400-2dbe-11eb-8399-7d1b14c1814c.png)

**Comment by fyl080801** [comment]
@zhongxi-tech version 1.5.0-beta.3 验证一下

**Comment by fyl080801** [comment]
@zhongxi-tech 已经更新，问题是否解决？

**Comment by zhongxi-tech** [comment]
@fyl080801 ，刚刚测试了一下，问题依旧，还没有解决的，我的联系方式我发到您的邮箱里面了

**Comment by zhongxi-tech** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fyl080801/vjdesign"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 下午4:23
收件人:&nbsp;"fyl080801/vjdesign"<vjdesign@noreply.github.com&gt;;
抄送:&nbsp;"中禧信息技术公司"<188633918@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [fyl080801/vjdesign] 点击“删除”无法出现删除对话框 (#31)





 
@zhongxi-tech master已经更新，问题是否解决？

**Comment by fyl080801** [comment]
废弃以前的弹窗方式，采用堆栈方式支持弹多个模态，再试试是否还会复现

**Comment by zhongxi-tech** [comment]
我找个时间试一试哦

**Comment by zhongxi-tech** [comment]
今晚直接用https://fyl080801.gitee.io/vjdesign/#/default，试了一下，发现还是会复现的

**Comment by fyl080801** [comment]
@zhongxi-tech 麻烦发一下这个层相关元素的computed样式吧  

![](https://tva1.sinaimg.cn/large/0081Kckwly1glrteq0ndcj315p0u04b6.jpg)

**Comment by David444588** [comment]
我也遇到这个问题
