### ISSUE TITLE
点击导出按钮无反应

### ISSUE THREAD

**Issue by lvsonghan** [fyl080801/vjdesign#34]
1、在下载的release及master分支里，导出按钮没有对应方法实现代码
2、在演示环境里，点击导出报错

**Comment by fyl080801** [comment]
目前还没有做导出功能

**Comment by lvsonghan** [comment]
> 目前还没有做导出功能

那请问下后续做的话是导出的json文件然后用v-jform读取展示是么

**Comment by fyl080801** [comment]
如果只是json数据，在元数据里就可以看，展示可用 [vjform](https://github.com/fyl080801/vjform) 或 [jformer](https://github.com/fyl080801/jformer)  

导出计划是生成一个html文件

**Comment by fyl080801** [comment]
@lvsonghan 示例已经追加导出功能
