### ISSUE TITLE
example can't run

### ISSUE THREAD

**Issue by jonahzheng** [fyl080801/vjdesign#71]
https://fyl080801.github.io/vjdesign/example/
![7A07BAC3-3074-4C91-9E36-F53B101A48EA](https://user-images.githubusercontent.com/5125282/222371575-f6f2acd9-e342-4fa2-8394-7ed26e67b715.png)

**Comment by fyl080801** [comment]
> https://fyl080801.github.io/vjdesign/example/ ![7A07BAC3-3074-4C91-9E36-F53B101A48EA](https://user-images.githubusercontent.com/5125282/222371575-f6f2acd9-e342-4fa2-8394-7ed26e67b715.png)

wrong npm package version, now fix it
